name: "Build"

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "true"
  
on:
  push:
    branches:
      - main
      - feat/*
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  app:
    name: ".NET App"
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./src
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04, windows-2022, macos-11 ]

    steps:
      - name: 🚚 Checkout latest
        uses: actions/checkout@v2

      - name: 🧲 Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: 📦 Install dependencies
        run: dotnet restore

      - name: 🔨 Build
        run: dotnet build --no-restore

      - name: 🧐 Test
        run: dotnet test --no-build --verbosity normal
  
  spa:
    name: "SPA App"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/Apps/NetPad.Apps.App/App
    
    strategy:
      matrix:
        node-version: [ 16.x, 18.x ]
    
    steps:
      - name: 🚚 Checkout latest
        uses: actions/checkout@v2

      - name: 🧲 Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: 📦 Install dependencies
        run: npm install

      - name: 🔨 Build
        run: npm run build

      - name: 🧐 Test
        run: npm test